CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS roles (
    key TEXT NOT NULL,
    primary key (key),
    unique (key)
);

INSERT INTO roles(key)
VALUES ('role.user'),
       ('role.admin');

CREATE TABLE IF NOT EXISTS users
(
    id               INT GENERATED BY DEFAULT AS IDENTITY,
    guid             UUID      default uuid_generate_v4() NOT NULL,
    email            TEXT                                 NOT NULL,
    is_active        BOOLEAN   DEFAULT FALSE,
    created_at       TIMESTAMP default now(),
    last_modified_at TIMESTAMP,
    deleted_at       TIMESTAMP,

    PRIMARY KEY (id, guid),
    UNIQUE (id),
    UNIQUE (guid),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id INT REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    role_key TEXT REFERENCES roles (key) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,

    primary key (user_id, role_key),
    UNIQUE (user_id, role_key)
);

CREATE TABLE IF NOT EXISTS user_profile
(
    id               INT GENERATED BY DEFAULT AS IDENTITY,
    user_id          INT REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    name             TEXT,
    phone_number     TEXT,
    company_name     TEXT,
    created_at       TIMESTAMP default now(),
    last_modified_at TIMESTAMP,
    deleted_at       TIMESTAMP
);